### ISSUE TITLE
[Feature request] Separate the setpoint and logs features to other extensions

### ISSUE THREAD

**Issue by madb1lly** [flatsiedatsie/square-theme#3]
Hi @flatsiedatsie,

I really like the additional logs features of this extension but I'm not so keen on the square theme itself. Would you consider splitting extension into 3?

- Square theme only
- Logs filtering and layering
- Thermostat setpoints

Cheers 🙂

**Comment by flatsiedatsie** [comment]
No I don't plan on doing that, sorry. That's way too much overhead.
